# Generated by Django 4.0.4 on 2022-05-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identifier_id',
            field=models.CharField(max_length=10, null=True, verbose_name='Identifier ID'),
        ),
    ]
