# Generated by Django 4.0.4 on 2022-05-10 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('status', models.CharField(choices=[('stand_by', 'Stand By'), ('active', 'Active'), ('closed', 'Closed')], max_length=10, verbose_name='status')),
                ('test_case', models.FileField(upload_to='', verbose_name='Test Case')),
                ('attachment', models.FileField(upload_to='', verbose_name='Attachment')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=500, verbose_name='Max Score')),
                ('due', models.DateTimeField(verbose_name='Due')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_distinct', models.BooleanField(verbose_name='')),
                ('score', models.DecimalField(decimal_places=2, max_digits=500, verbose_name='Score')),
                ('file', models.FileField(upload_to='', verbose_name='')),
                ('description', models.TextField()),
                ('result', models.JSONField()),
                ('submitted', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='evaluator.assignment', verbose_name='Assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Data')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criteria', to='evaluator.assignment', verbose_name='Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='evaluator.submission', verbose_name='Submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('status', models.CharField(choices=[('stand_by', 'Stand By'), ('active', 'Active'), ('closed', 'Closed')], max_length=10, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('instructors', models.ManyToManyField(related_name='classrooms_instructors', to=settings.AUTH_USER_MODEL, verbose_name='Instructors')),
                ('students', models.ManyToManyField(related_name='classrooms_students', to=settings.AUTH_USER_MODEL, verbose_name='Students')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='evaluator.classroom', verbose_name='Classroom'),
        ),
    ]
