# Generated by Django 4.0.4 on 2022-05-14 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='classrooms_instructors', to=settings.AUTH_USER_MODEL, verbose_name='Instructors'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classrooms_students', to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
    ]
